listNomes = [
    "emma"   ,
    "sandro" ,
    "vasile" ,
    "lepo"   ,
    "joane"  ,
    "lara"   ,
    "mark"   ,
    "luiz"   ,
    "sasha"  ,
    "anna"   ,
    "ricardo",
    "peter"  ,
    "erika"  ,
    "denyse" ,
    "gabriel",
    "denis"  ,
    "bocsa"  ,
    "sangelo",
    "ronaldo",
    "philip" ,
    "david"  ,
    "sergey" ,
    "ivan"   ,
    "andrii" ,
    "kevin"  ,
    "rafael" ,
    "thomas" ,
    "tom"    ,
    "belchior",
    "mary"   ,
    "vera"   ,
    "sinatra",
    "oscar"  ,
    "sett"   ,
    "morgana",
    "karolyne",
    "alex"   ,
    "ievgenn",
    "dari"   ,
    "isacc"  ,
]

listNacio = [
    "American",
    "British",
    "Canadian",
    "Australian",
    "French",
    "German",
    "Italian",
    "Spanish",
    "Mexican",
    "Brazilian",
    "Argentinian",
    "Chinese",
    "Japanese",
    "South Korean",
    "Russian",
    "Indian",
    "Swiss",
    "Swedish",
    "Norwegian",
    "Danish",
    "Finnish",
    "Dutch",
    "Belgian",
    "Irish",
    "Scottish",
    "Welsh",
    "Portuguese",
    "Greek",
    "Turkish",
    "Israeli",
    "Saudi Arabian",
    "Emirati",
    "Qatari",
    "Kuwaiti",
    "Omani",
    "Egyptian",
    "Moroccan",
    "Tunisian",
    "Algerian",
    "South African",
    "Kenyan",
    "Nigerian",
    "Ghanaian",
    "Ethiopian",
    "Ugandan",
    "Zimbabwean",
    "Australian",
    "New Zealander"
]

listNomEsc = [
    "Escola Secundária de Camões",
    "Escola Secundária Dona Filipa de Lencastre",
    "Escola Secundária de Santo António",
    "Escola Secundária António Arroio",
    "Escola Secundária de Alvalade",
    "Escola Secundária de Pedro Nunes",
    "Escola Secundária Padre António Vieira",
    "Escola Secundária Rainha Dona Amélia",
    "Escola Secundária D. Dinis",
    "Escola Secundária Eça de Queirós",
    "Escola Secundária Luís de Camões",
    "Escola Secundária Vergílio Ferreira",
    "Escola Secundária Gil Vicente",
    "Escola Secundária José Gomes Ferreira",
    "Escola Secundária Quinta do Marquês",
    "Escola Secundária José Afonso",
    "Escola Secundária de Restelo",
    "Escola Secundária da Amadora",
    "Escola Secundária D. João de Castro",
    "Escola Secundária Padre Alberto Neto"
]

listMat = [
    "Matemática",
    "Português",
    "Inglês",
    "Ciências",
    "História",
    "Geografia",
    "Biologia",
    "Física",
    "Química",
    "Educação Física",
    "Artes",
    "Música",
    "Filosofia",
    "Sociologia",
    "Educação Moral e Cívica",
    "Tecnologias de Informação e Comunicação",
    "Educação Visual",
    "Educação Tecnológica",
    "Língua Estrangeira (varie de acordo com o idioma estudado)",
    "Economia",
    "Gestão",
    "Psicologia",
    "Antropologia",
    "Literatura",
    "Teatro",
    "Educação para a Saúde",
    "Educação Ambiental",
    "Desenho Técnico",
    "Programação",
    "Robótica",
    "Educação Alimentar",
    "Estudo Acompanhado",
    "Tutoria",
    "Projeto Interdisciplinar"
]

listNomRest = [
    "Adega Velha",
    "Cantinho Lusitano",
    "Tasca do Chico",
    "Taberna da Rua das Flores",
    "O Prego da Peixaria",
    "Ramiro",
    "Solar dos Presuntos",
    "Cervejaria Trindade",
    "Belcanto",
    "Bairro do Avillez",
    "Alma",
    "100 Maneiras",
    "Sea Me",
    "Cantinho do Avillez",
    "Taberna Moderna",
    "Taberna da Rua das Flores",
    "Cervejaria Ramiro",
    "A Valenciana",
    "Casa do Alentejo",
    "Restaurante Laurentina",
    "Forno Velho",
    "Cervejaria O Zapata",
    "Cervejaria Portugália",
    "Casa Portuguesa do Pastel de Bacalhau",
    "Chapitô à Mesa",
    "O Poleiro",
    "O Talho",
    "A Cevicheria",
    "A Cultura do Hamburguer",
    "Aromas e Temperos",
    "Salsa e Coentros",
    "Solar dos Nunes",
    "A Mercearia",
    "Fábulas",
    "O Lugar",
    "A Gina",
    "A Provinciana",
    "A Travessa",
    "Alfacinha",
    "Tágide"
]

listLing = [
    "Python",
    "JavaScript",
    "Java",
    "C++",
    "C#",
    "Swift",
    "Go",
    "Ruby",
    "PHP",
    "TypeScript",
    "Rust",
    "Kotlin",
    "HTML",
    "CSS",
    "SQL",
    "Shell Script",
    "Objective-C",
    "Perl",
    "Scala",
    "Lua",
    "BrainFuck"
]

listPartidos = [
    "Partido Socialista (PS)",
    "Partido Social Democrata (PSD)",
    "Bloco de Esquerda (BE)",
    "Partido Comunista Português (PCP)",
    "CDS - Partido Popular (CDS-PP)",
    "PAN - Pessoas-Animais-Natureza",
    "Iniciativa Liberal (IL)",
    "Chega",
    "LIVRE",
    "Partido Ecologista (PEV)",
    "Aliança",
    "Partido Democrático Republicano (PDR)",
    "Partido Nacional Renovador (PNR)",
    "Partido Comunista dos Trabalhadores Portugueses (PCTP-MRPP)",
    "Nós, Cidadãos!",
    "Partido da Terra (MPT)",
    "Volt Portugal",
    "Partido Operário de Unidade Socialista (POUS)",
    "Partido Popular Monárquico (PPM)",
    "Movimento Alternativa Socialista (MAS)"
]

listPatentesMilitares = [
    "Soldado",
    "Cabo",
    "Cabo-chefe",
    "Sargento",
    "Subtenente",
    "Tenente",
    "Capitão",
    "Major",
    "Tenente-coronel",
    "Coronel",
    "General de Brigada",
    "General de Divisão",
    "General de Exército",
    "Marechal"
]